# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

team_id ENV["MY_PORTAL_TEAM_ID"]
team_name ENV["MY_PORTAL_TEAM_NAME"]

platform :ios do

  app_id = ENV["MY_BUNDLE_IDENTIFIER"]

  desc "Renew a push notification certificate"
  lane :renew_push_certificate do
    get_push_certificate(
      development: false,
      app_identifier: app_id,
      pem_name: "#{app_id}.pem",
      output_path: "apns",
      active_days_limit: 30,
      p12_password: "",
      force: true,  # <=== For debug ===
      new_profile: proc do |profile_path|
        # 生成後の処理
      end,
    )
  end

  desc "Test lane with fastlane spaceship"
  lane :test do
    Spaceship::Portal.login
    Spaceship::Portal.select_team
    app = Spaceship::Portal.app.find(ENV["MY_BUNDLE_IDENTIFIER"])
    puts app
  end
end
